// Sap xep theo thu tu phuc tap cua thuat toan
//        2^10	    	-> O(1)
//        2^logn		-> O(n)
//        4n			-> O(n)
//        3n + 100logn	-> O(n)
//        nlogn			-> O(nlogn)
//        4nlogn + 2n	-> O(nlogn)
//        n^2 + 10n		-> O(n^2)
//        n^3			-> O(n^3)
//        2^n			-> O(2^n)
